# Generated by Django 3.0.2 on 2020-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('categoryname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_count', models.IntegerField()),
            ],
        ),
    ]
