# Generated by Django 3.0.2 on 2020-04-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200424_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('categoryname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_count', models.IntegerField()),
                ('img_file', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
