# Generated by Django 3.0.2 on 2020-04-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200425_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.courses')),
            ],
        ),
    ]
