# Generated by Django 3.0.2 on 2020-04-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_coursecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='video_file',
            field=models.FileField(default='not available', upload_to='videos/', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='enrollDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.courses')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserDetails', to_field='name')),
            ],
        ),
    ]
