# Generated by Django 3.0.2 on 2020-04-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200425_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='text_file',
            field=models.FileField(default='not available', upload_to='files/', verbose_name=''),
            preserve_default=False,
        ),
    ]
