# Generated by Django 3.0.2 on 2020-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20200425_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='video_file',
            field=models.FileField(default='not available', upload_to='videos/', verbose_name=''),
        ),
    ]
