# Generated by Django 3.0.2 on 2020-04-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20200425_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='enrolldetails',
            name='status',
            field=models.CharField(default='in progress', max_length=100),
        ),
        migrations.CreateModel(
            name='coursevideocontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='')),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.courses')),
            ],
        ),
    ]
